# Generated by Django 5.2.17 on 2026-08-25 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_or_session', models.CharField(blank=True, max_length=64)),
                ('event_type', models.CharField(max_length=64)),
                ('object_identifier', models.CharField(blank=True, max_length=64)),
                ('model_version', models.CharField(blank=True, max_length=64)),
                ('questionnaire_version', models.CharField(blank=True, max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModelVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('semantic_version', models.CharField(max_length=32)),
                ('model_class_path', models.CharField(max_length=255)),
                ('coefficient_json', models.JSONField(default=dict)),
                ('predictor_definitions', models.JSONField(blank=True, default=dict)),
                ('action_zone_metadata', models.JSONField(blank=True, default=dict)),
                ('validation_status', models.CharField(default='illustrative_only', max_length=64)),
                ('clinical_use_permitted', models.BooleanField(default=False)),
                ('checksum', models.CharField(blank=True, max_length=128)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('name', 'semantic_version')},
            },
        ),
        migrations.CreateModel(
            name='QuestionnaireVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('semantic_version', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('frozen', 'Frozen'), ('retired', 'Retired')], default='draft', max_length=16)),
                ('item_definition', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('frozen_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('name', 'semantic_version')},
            },
        ),
    ]
